### ISSUE TITLE
Add MunkiPkg to projects listed on munki.org

### ISSUE THREAD

**Issue by homebysix** [munki/munki.github.io#1]

**Comment by gregneagle** [comment]
Before that could happen, a page for munki-pkg would need to be created here: https://www.munki.org/munki-pkg/ ? To match:
https://www.munki.org/munki/
https://www.munki.org/munkiwebadmin/
https://www.munki.org/createOSXinstallPkg/

I suppose for now it could just link to https://github.com/munki/munki-pkg#munkipkg

**Comment by gregneagle** [comment]
Done.
